# [processor.pyrefly]

[processor.ruff]

# [processor.markdownlint]

[processor.slidev]

[processor.zspell]

[processor.taplo]

[processor.pylint]

[processor.yq]

[processor.yamllint]

[processor.aspell]

[processor.mypy]

[processor.markdown]
